version: "0.2"

env:
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
      - cargo install cargo-lambda
  build:
    commands:
      - cd translate
      - make

artifacts:
  files:
    - translate/target/lambda/app/*
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*