version: "0.2"

env:
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
  build:
    commands:
      - cd translate
      - cargo build --release --bin app
      - mv target/release/app target/release/bootstrap

artifacts:
  files:
    - translate/target/release/*
    - bin/*
    - stack/*
    - package.json
    - tsconfig.json
    - cdk.json
    - jest.config.js
  discard-paths: "no"

cache:
  paths:
    - $HOME/.cargo/registry/**/*