[package]
name = "tl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui-textarea = "*"
ratatui = "0.25"
crossterm = "*"
tokio = {  version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["rustls-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"