[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-translate = "1.3.0"
env_logger = "0.10.1"
lambda-web = { version = "0.2.1", features = ["actix4"] }
actix-web = "4.4.0"
serde = "1"
serde_json = "1"