[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-translate = "1.3.0"
env_logger = "0.10.1"
actix-web = "4.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aws-types = "1.0.1"
aws-config = "1.0.1"
async-stream = "0.3.1"
scraper = "0.18"
reqwest = "0.11"
html5ever = "0.26"
nipper = "0.1"